### ISSUE TITLE
Docker build fails on arm64 due to Phantom.js lack of support

### ISSUE THREAD

**Issue by hugo-gomes** [hivesolutions/headless#13]
## Description

The build process fails when attempting to build the Docker images provided by the `headless` project on an arm64 architecture system. This issue is due to the need for arm64 support from Phantom.js, one of the back-end engines utilized by the project for rendering images and PDFs from HTML.

## Expected Behavior

The Docker build process should be completed successfully on arm64 architecture, allowing the `headless` project to be used in such environments.

## Actual Behavior

The build process fails on arm64 systems because Phantom.js does not provide binaries compatible with this architecture.

## Possible Solutions

**Conditional Dependency Management:** Implement logic within the Dockerfile or build scripts to skip the installation of Phantom.js or use alternative methods when detecting an arm64 architecture.
**Documentation:** Update the project's documentation to indicate the current architecture limitations and provide guidance or workarounds for arm64 system users.

**Comment by joamag** [comment]
@hugo-gomes posting here the current error

```
PhantomJS is not installed, the Phantom engine will not be available
2024-02-27 18:25:49,43 [INFO] Listening on 0.0.0.0:8080
2024-02-27 18:25:49,66 [INFO] Exiting on user's request
/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:267
                reject(new Error([
                       ^

Error: Failed to launch the browser process!
rosetta error: failed to open elf at /lib64/ld-linux-x86-64.so.2
 


TROUBLESHOOTING: https://pptr.dev/troubleshooting

    at Interface.onClose (/app/node_modules/@puppeteer/browsers/lib/cjs/launch.js:267:24)
    at Interface.emit (node:events:529:35)
    at Interface.close (node:internal/readline/interface:534:10)
    at Socket.onend (node:internal/readline/interface:260:10)
    at Socket.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.19.1
```

**Comment by hugo-gomes** [comment]
@joamag Google Chrome has no arm64 version available for Linux. https://github.com/GoogleChromeLabs/chrome-for-testing?tab=readme-ov-file#json-api-endpoints

```
The current list of supported platforms is:
* linux64
* mac-arm64
* mac-x64
* win32
* win64
```

However, Chromium does have an arm64 version for Linux: https://chromium.googlesource.com/chromium/src/+/master/docs/linux/chromium_packages.md

PS: Chrome has recently launched an arm version for Windows - https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/native-chromium-builds-windows-on-arm

**Comment by joamag** [comment]
How can we install the arm64 Chromium to use for puppeteer?

**Comment by hugo-gomes** [comment]
The official puppeteer image, which includes [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/), does not have an arm64 image available - https://github.com/puppeteer/puppeteer/pkgs/container/puppeteer/183435219?tag=22.3.0

@joamag we can add Chromium by installing it from Debian and Ubuntu official repositories for ARM architectures:
* https://packages.ubuntu.com/jammy/chromium-browser
* https://packages.debian.org/bookworm/chromium

Additionally, both Dockerfiles will need to set `PUPPETEER_SKIP_CHROME_DOWNLOAD` and `PUPPETEER_EXECUTABLE_PATH` accordingly.

Replacing Chrome with Chromium is not a drop-in replacement since there are some differences:
* https://www.howtogeek.com/202825/whats-the-difference-between-chromium-and-chrome/#what-chrome-has-that-chromium-doesn-t
* https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/chromium_browser_vs_google_chrome.md

**Comment by joamag** [comment]
Maybe we should create a separate dockerfile just for other cou archs and use the strategy you're mentioning

**Comment by joamag** [comment]
This is now considered solved by https://github.com/hivesolutions/headless/pull/17
